#!/usr/bin/env node
// arch-client generator (seed design, choices 6–7): an OpenRPC 1.3 document with an `x-arch-events`
// block → src/generated/{types,methods,events,index}.ts. Output is committed; `--check` fails when
// regenerating would change it. With no schema pinned, the output is the honest empty module.
//
//   node scripts/generate.mjs [--schema <file>] [--out <dir>] [--check]
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';

const here = dirname(fileURLToPath(import.meta.url));
const argv = process.argv.slice(2);
const opt = (flag, dflt) => (argv.includes(flag) ? argv[argv.indexOf(flag) + 1] : dflt);
const schemaPath = resolve(opt('--schema', join(here, '..', 'schema', 'arch-api.json')));
const outDir = resolve(opt('--out', join(here, '..', 'src', 'generated')));
const check = argv.includes('--check');

const HEADER = (version) => `// Generated by @tau-rs/arch-client from arch-api.json (schema ${version}). Do not edit: run \`npm run generate\`.\n`;

const refName = (schema) => (schema && typeof schema.$ref === "string" && schema.$ref.startsWith("#/components/schemas/")) ? schema.$ref.slice("#/components/schemas/".length) : undefined;
const pascal = (name) => name.split(/[^A-Za-z0-9]+/).filter(Boolean).map(s => s[0].toUpperCase() + s.slice(1)).join('');
const rewriteRefs = (node) => {
    if (Array.isArray(node)) { return node.map(rewriteRefs); }
    if (node && typeof node === 'object') {
        const out = {};
        for (const [k, v] of Object.entries(node)) {
            out[k] = k === '$ref' && typeof v === 'string' ? v.replace('#/components/schemas/', '#/$defs/') : rewriteRefs(v);
        }
        return out;
    }
    return node;
};

const stripNoise = (ts) => ts
    .replace(/export interface ArchApiRoot \{\s*\}\n?/, '')
    .replace(/\/\*\*\n(?:\s*\*[^\n]*\n)*?\s*\*\/\n(?=export )/g, block => /was referenced by/.test(block) ? '' : block)
    .replace(/\n{3,}/g, '\n\n');

export async function generate(doc) {
    if (!doc) {
        return { 'index.ts': HEADER('none') + `export const SCHEMA_VERSION = 'none';\n// no schema pinned yet (schema/schema.lock.json): no methods, no events\nexport interface Methods {}\nexport interface Events {}\n` };
    }
    if (typeof doc.openrpc !== 'string' || !Array.isArray(doc.methods)) {
        throw new Error('arch-api.json is not an OpenRPC document (needs `openrpc` and `methods`)');
    }
    const version = doc.info?.version ?? 'unknown';
    const defs = { ...rewriteRefs(doc.components?.schemas ?? {}) };
    const methods = [];
    for (const m of doc.methods) {
        const base = pascal(m.name);
        const params = m.params ?? [];
        let paramsType = 'undefined';
        if (params.length > 0) {
            defs[`${base}Params`] = {
                type: 'object', additionalProperties: false,
                properties: Object.fromEntries(params.map(p => [p.name, rewriteRefs(p.schema)])),
                required: params.filter(p => p.required).map(p => p.name),
            };
            paramsType = `${base}Params`;
        }
        const resultRef = refName(m.result?.schema);
        if (!resultRef) { defs[`${base}Result`] = rewriteRefs(m.result?.schema ?? { type: 'null' }); }
        methods.push({ name: m.name, paramsType, resultType: resultRef ?? `${base}Result` });
    }
    const events = [];
    for (const e of doc['x-arch-events'] ?? []) {
        const payloadRef = refName(e.payload);
        const t = payloadRef ?? `${pascal(e.name)}Payload`;
        if (!payloadRef) { defs[t] = rewriteRefs(e.payload ?? { type: 'null' }); }
        events.push({ name: e.name, payloadType: t });
    }
    const root = { title: 'ArchApiRoot', type: 'object', properties: {}, additionalProperties: false, $defs: defs };
    const types = await compile(root, 'ArchApiRoot', { bannerComment: '', unreachableDefinitions: true, additionalProperties: false, format: true, style: { singleQuote: true, semi: true, tabWidth: 4, printWidth: 110 } });
    const used = new Set([...methods.flatMap(m => [m.paramsType, m.resultType]), ...events.map(e => e.payloadType)].filter(t => t !== 'undefined'));
    const imports = (names) => names.length ? `import type { ${names.join(', ')} } from './types';\n\n` : '';
    const methodNames = [...new Set(methods.flatMap(m => [m.paramsType, m.resultType]).filter(t => t !== 'undefined'))];
    const eventNames = events.map(e => e.payloadType);
    void used;
    return {
        'types.ts': HEADER(version) + stripNoise(types).trimEnd() + '\n',
        'methods.ts': HEADER(version) + imports(methodNames)
            + `export interface Methods {\n${methods.map(m => `    '${m.name}': { params: ${m.paramsType}; result: ${m.resultType} };`).join('\n')}\n}\n\n`
            + `export const METHODS = [${methods.map(m => `'${m.name}'`).join(', ')}] as const;\n`,
        'events.ts': HEADER(version) + imports(eventNames)
            + `export interface Events {\n${events.map(e => `    '${e.name}': ${e.payloadType};`).join('\n')}\n}\n\n`
            + `export const EVENTS = [${events.map(e => `'${e.name}'`).join(', ')}] as const;\n`,
        'index.ts': HEADER(version) + `export const SCHEMA_VERSION = '${version}';\nexport * from './types';\nexport * from './methods';\nexport * from './events';\n`,
    };
}

const main = async () => {
    const doc = existsSync(schemaPath) ? JSON.parse(readFileSync(schemaPath, 'utf8')) : undefined;
    if (!doc) { console.log(`generate: no schema at ${schemaPath}; emitting the empty module`); }
    const files = await generate(doc);
    if (check) {
        const onDisk = existsSync(outDir) ? readdirSync(outDir).filter(f => f.endsWith('.ts')) : [];
        const drift = [];
        for (const [name, content] of Object.entries(files)) {
            if (!existsSync(join(outDir, name)) || readFileSync(join(outDir, name), 'utf8') !== content) { drift.push(name); }
        }
        for (const f of onDisk) { if (!(f in files)) { drift.push(`${f} (stale)`); } }
        if (drift.length) { console.error(`generate --check: drift in ${outDir}: ${drift.join(', ')}. Run \`npm run generate\` and commit.`); process.exit(1); }
        console.log('generate --check: generated client is current');
        return;
    }
    mkdirSync(outDir, { recursive: true });
    for (const f of existsSync(outDir) ? readdirSync(outDir) : []) { if (f.endsWith('.ts') && !(f in files)) { writeFileSync(join(outDir, f), ''); } }
    for (const [name, content] of Object.entries(files)) { writeFileSync(join(outDir, name), content); }
    console.log(`generate: wrote ${Object.keys(files).join(', ')} to ${outDir}`);
};

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    main().catch(e => { console.error(e.message); process.exit(1); });
}
