import { strict as assert } from 'node:assert';
import { test } from 'node:test';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generate } from './generate.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const example = JSON.parse(readFileSync(join(here, '..', 'test', 'example', 'arch-api.example.json'), 'utf8'));

test('no schema → the empty module, versioned none', async () => {
    const files = await generate(undefined);
    assert.deepEqual(Object.keys(files), ['index.ts']);
    assert.match(files['index.ts'], /SCHEMA_VERSION = 'none'/);
    assert.match(files['index.ts'], /export interface Methods \{\}/);
});

test('an OpenRPC document → types, a Methods map, an Events map, the schema version', async () => {
    const files = await generate(example);
    assert.deepEqual(Object.keys(files).sort(), ['events.ts', 'index.ts', 'methods.ts', 'types.ts']);
    assert.match(files['index.ts'], /SCHEMA_VERSION = '0\.1'/);
    assert.match(files['types.ts'], /export interface Clock \{/);
    assert.match(files['types.ts'], /export type Label = string/);
    assert.match(files['types.ts'], /export interface ClockSetParams \{\s*at: number;\s*label\?: Label;/);
    assert.match(files['types.ts'], /export interface TickPayload \{\s*at: number;/);
    assert.match(files['methods.ts'], /'ping': \{ params: undefined; result: PingResult \}/);
    assert.match(files['methods.ts'], /'clock\.set': \{ params: ClockSetParams; result: Clock \}/);
    assert.match(files['methods.ts'], /METHODS = \['ping', 'clock\.set'\] as const/);
    assert.match(files['events.ts'], /'tick': TickPayload/);
    for (const f of Object.values(files)) { assert.match(f, /^\/\/ Generated by @tau-rs\/arch-client/); }
});

test('generation is deterministic', async () => {
    assert.deepEqual(await generate(example), await generate(example));
});

test('a document that is not OpenRPC is refused', async () => {
    await assert.rejects(generate({ swagger: '2.0' }), /not an OpenRPC document/);
});

test('the generated example compiles under strict TypeScript', async () => {
    const files = await generate(example);
    const dir = mkdtempSync(join(tmpdir(), 'arch-client-gen-'));
    for (const [name, content] of Object.entries(files)) { writeFileSync(join(dir, name), content); }
    const tsc = join(here, '..', '..', '..', 'node_modules', '.bin', 'tsc'); // hoisted by npm workspaces
    execFileSync(tsc, ['--noEmit', '--strict', '--target', 'ES2022', '--module', 'commonjs', ...Object.keys(files).map(f => join(dir, f))], { stdio: 'pipe' });
});
